//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int idCategoria { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
